global.jQuery = require('jquery');
require('bootstrap');
require('./js/smoothslider');
require('./js/loader');
require('./js/AnimateHeader');
require('./js/header');
require('./js/navigator');
require('./js/chart');
require('./js/slideshow');
require('./js/filter');
require('./js/contact');